# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jademon/Documents/GitHub/megalib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jademon/Documents/GitHub/megalib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jademon/Documents/GitHub/megalib/CMakeFiles /Users/jademon/Documents/GitHub/megalib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jademon/Documents/GitHub/megalib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eview

# Build rule for target.
eview: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eview
.PHONY : eview

# fast build rule for target.
eview/fast:
	$(MAKE) $(MAKESILENT) -f src/eview/CMakeFiles/eview.dir/build.make src/eview/CMakeFiles/eview.dir/build
.PHONY : eview/fast

#=============================================================================
# Target rules for targets named geomega

# Build rule for target.
geomega: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 geomega
.PHONY : geomega

# fast build rule for target.
geomega/fast:
	$(MAKE) $(MAKESILENT) -f src/geomega/CMakeFiles/geomega.dir/build.make src/geomega/CMakeFiles/geomega.dir/build
.PHONY : geomega/fast

#=============================================================================
# Target rules for targets named mimrec

# Build rule for target.
mimrec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimrec
.PHONY : mimrec

# fast build rule for target.
mimrec/fast:
	$(MAKE) $(MAKESILENT) -f src/mimrec/CMakeFiles/mimrec.dir/build.make src/mimrec/CMakeFiles/mimrec.dir/build
.PHONY : mimrec/fast

#=============================================================================
# Target rules for targets named realta

# Build rule for target.
realta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 realta
.PHONY : realta

# fast build rule for target.
realta/fast:
	$(MAKE) $(MAKESILENT) -f src/realta/CMakeFiles/realta.dir/build.make src/realta/CMakeFiles/realta.dir/build
.PHONY : realta/fast

#=============================================================================
# Target rules for targets named response

# Build rule for target.
response: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 response
.PHONY : response

# fast build rule for target.
response/fast:
	$(MAKE) $(MAKESILENT) -f src/response/CMakeFiles/response.dir/build.make src/response/CMakeFiles/response.dir/build
.PHONY : response/fast

#=============================================================================
# Target rules for targets named revan

# Build rule for target.
revan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 revan
.PHONY : revan

# fast build rule for target.
revan/fast:
	$(MAKE) $(MAKESILENT) -f src/revan/CMakeFiles/revan.dir/build.make src/revan/CMakeFiles/revan.dir/build
.PHONY : revan/fast

#=============================================================================
# Target rules for targets named sivan

# Build rule for target.
sivan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sivan
.PHONY : sivan

# fast build rule for target.
sivan/fast:
	$(MAKE) $(MAKESILENT) -f src/sivan/CMakeFiles/sivan.dir/build.make src/sivan/CMakeFiles/sivan.dir/build
.PHONY : sivan/fast

#=============================================================================
# Target rules for targets named spectralyze

# Build rule for target.
spectralyze: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spectralyze
.PHONY : spectralyze

# fast build rule for target.
spectralyze/fast:
	$(MAKE) $(MAKESILENT) -f src/spectralyze/CMakeFiles/spectralyze.dir/build.make src/spectralyze/CMakeFiles/spectralyze.dir/build
.PHONY : spectralyze/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... eview"
	@echo "... geomega"
	@echo "... mimrec"
	@echo "... realta"
	@echo "... response"
	@echo "... revan"
	@echo "... sivan"
	@echo "... spectralyze"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

